package com.hengyunsoft.commons.exception.core;

import com.hengyunsoft.exception.code.BaseExceptionCode;

/**
 * 交换共享（exchange项目）相关的异常代码
 * 85000-90000
 */
public enum ExchangeExceptionCode implements BaseExceptionCode {
    //数据目录相关 85000^85499
    DIRECTORY_ID_NULL(85000, "数据目录ID不允许为空"),
    DIRECTORY_NAME_NULL(85001, "数据目录名称不允许为空"),
    DIRECTORY_CODE_NULL(85002, "数据目录编码不允许为空"),
    DIRECTORY_TYPE_NULL(85003, "数据目录标识名称不允许为空"),
    DIRECTORY_PARENTID_NULL(85011, "数据目录父id不允许为空"),
    DIRECTORY_ENTITY_NULL(85009,"数据目录对象不能为空"),
    DIRECTORY_ADMIN_NULL(85010,"需要平台管理员才能操作"),
    DIRECTORY_UNITID_NULL(85012, "单位id不允许为空"),
    DIRECTORY_DATA_TYPE_NULL(85013, "数据类型不能为空"),
    DIRECTORY_NOT_FIND(85014, "没有找到对应的目录"),


    //数据目录元数据异常编码
    DIRECTORY_FILEID_NAME_NULL(85004,"元数据名称不能为空"),
    DIRECTORY_FILEID_TYPE_NULL(85005,"元数据字段类型不能为空"),
    DIRECTORY_FILEID_CODE_NULL(85006,"元数据字段标识不能为空"),
    DIRECTORY_SET_FILEID_NULL(85007,"元数据数据集字段不能为空"),
    DIRECTORY_FILEID_ID_NULL(85008,"元数据ID不能为空"),
    DIRECTORY_FILEID_LENGTH_NULL(85009,"元数据长度不能为空"),
    DIRECTORY_NOT_USE(85010,"元目录不可用"),
    DIRECTORY_NOT_UNION_SET(85011,"该API所在目录没有关联数据集，不可调用"),

    //api相关 86000^86499
    DEMAND_NULL(86000,"需求对象不能为空" ),
    HDDEPT_NULL(86001,"处理部门不能为空"),
    DEMAND_CONTENT_NULL(86002,"申请内容不能为空"),
    DEMAND_ID_NULL(86003,"需求Id不能为空"),
    DEMAND_ELEMENT_SET_NULL(86004,"返回对象不能为空"),
    API_ID_NULL(86005,"API id不能为空"),
    API_ELEMENT_ID_NULL(86006,"API 返回字段不能为空"),
    API_NAME_NULL(86007,"API 名称不能为空"),
    API_DATA_FORMAT_NULL(86008,"API 支持格式不能为空"),
    API_STATUS_NULL(86009,"API 状态不能为空"),
    SHARE_APPLY_NULL(86010,"共享申请对象不能为空"),
    SHARE_APPLY_LIMIT_NULL(86011,"共享申请授权期限不能为空"),
    SHARE_APPLY_ID_NULL(86012,"共享申请Id不能为空"),
    SHARE_APPLY_TAKE_NULL(86013,"订阅状态不能为空"),
    SHARE_APPLY_STEP_NULL(86014,"错误操作，请先目录选择"),
    SHARE_APPLY_FITER_NULL(86015,"过滤对象不能为空"),
    SHARE_APPLY_APIID_NOT_EXIST(86016,"输入API ID不能为空"),
    SHARE_DICT_NULL(86017,"申请对象不能为空"),
    SHARE_DICT_DICTNAME_NULL(86018,"输入API 目录名称不能为空"),
    SHARE_DICT_DICTCODE_NULL(86019,"输入API 目录编码不能为空"),
    SHARE_DICT_PDICTCODE_NULL(86020,"输入API 上级目录不能为空"),
    SHARE_DICT_ID_NULL(86021,"输入API ID不能为空"),
    SHARE_AUTO_UNIT_ENTITY_NULL(86022,"API授权对象不能为空"),
    SHARE_API_EXCEPTION_ID_NULL(86023,"API异常ID不能为空"),
    SHARE_API_SECRET_KEY_NULL(86024,"API密钥不能为空"),
    SHARE_API_APPLY_OVERDUE(86025,"该API申请已经过期，请重新申请"),
    SHARE_API_SECRET_NOT_EXIST(86026,"没有匹配的API信息，请检查密钥"),
    SHARE_API_NOT_EXIST(86027,"找不到对应的API"),
    SHARE_SET_NOT_EXIST(86028,"找不到对应的数据集"),
    SELECT_FILED_NOT_EXIST(86029,"找不到对应的查询字段"),
    SELECT_TABLE_NOT_EXIST(86030,"数据集表配置错误"),
    DICT_CODE_YEW_EXIST(86031,"该编码已经存在"),
    SHARE_API_CODE_NULL(86032,"输入API 编码不能为空"),
    API_IS_FORBIDDEN(86033,"API 已被禁用"),
    API_NO_AUTH(86034,"无权访问该API"),
    DATE_FORMAT_ERROR(86035,"请传入正确的日期格式，标准格式为yyyy-MM-dd hh24:mi:ss(例：2018-2-10 10:00:00)"),








    //流程相关 86500^86599
    TASK_ID_NULL(86500,"任务Id不能为空"),
    TASK_HANDLE_STATUS_NULL(86501,"处理状态不能为空"),
    DEMAND_ESTIMATE_TIME_NULL(86502,"预计封装API时间不能为空"),
    TASK_HANDLE_ENTITY_NULL(86503,"审批对象不能为空"),
    TASK_ID_NOT_EXIST(86504,"任务ID不存在"),
    TASK_HANDLE_TYPE_NULL(86505,"处理类型不能为空"),
    TASK_APPLY_NULL(86506,"找不到该业务对应的申请信息"),
    TASK_API_USER_NULL(86507,"没有找到相关联的API申请信息"),
    TASK_APPLY_CODE_NULL(86508,"申请编码不能为空"),


    //数据集相关 85500^85599
    CREATEDATASET_CREATEDSPDBDTO_DBID(85500," 数据源id,不能为空"),
    CREATEDATASET_CREATEDSPDBDTO_UPDATETYPE(85501," 更新方式不能为空"),
    CREATEDATASET_CREATEDSPDBDTO_API_FAILED(85502," API调用失败"),
    CREATEDATASET_CREATEDSPDBDTO_API_TYOE_ERROR(85503," API返回类型错误，只能是1和2"),
    CREATEDATASET_CREATEDATASETPARAMFILEDTO_DATASET_NOT(85504,"数据集不存在"),
    CREATEDATASET_CREATEDATASETPARAMDTO_SQL_ERROR(85505,"SQL语句错误"),
    CREATEDATASET_CREATEDATASETPARAMDTO_TYPE_ERROR(85506," 创建数据集类型错误,只能是1到4"),
    CREATEDATASET_CREATEDATASETPARAMDTO_SQL_TYPE_ERROR(85507,"创建数据集方式错误,只是能1和2"),
    CREATEDATASET_CREATEDATASETPARAMDTO_HAS_NOT_FIELD(85508,"选择的字段在表中不存在"),
    CREATEDATASET_CREATEDATASETPARAMDTO_ROLUE_FIELD(85509,"选择的参数规则不存在"),
    CREATEDATASET_CREATEDATASETPARAMDTO_DIR_FIELD(85510,"目录id不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_PAGE_FIELD(85511,"请求页不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_DATA_GET_ERROR(85512,"API或者数据库类型的数据集才能调用数据"),
    CREATEDATASET_CREATEDATASETPARAMDTO_FLOWS_NOT_PASS(85513,"当前数据集没有审批通过不能查询数据"),
    CREATEDATASET_CREATEDATASETPARAMDTO_PAGE_PARAM_NULL(85514,"查询参数不能为空"),
    CREATEDATASET_OPT_NEED_UNIT_ADMIN(85515,"需要单位管理员或者平台管理员才能操作"),
    CREATEDATASET_OPT_NEED_DATA_OPT(85516,"没有创建数据集权限"),
    CREATEDATASET_OPT_CAN_NOT(85517,"该数据集不能删除"),
    DATA_SET_ID_NULL(85518,"数据集id不能为空"),
    API_QUERY_DATA_URL_NULL(85519,"url不能为空"),
    API_QUERY_DATA_RES_TYPE_NULL(85520,"返回值类型不能空"),
    CREATEDATASET_SET_CODE_DOUBLE(85521,"集合编码重复"),

    CREATEDATASET_CREATEDATASETPARAMDTO_EDITTYPE(85522,"编辑类型,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_ID(85523,"主键数据集id,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_SETNAME(85524,"数据集名称,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_SETCODE(85525,"数据集标识,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_SETTYPE(85526,"数据集类型,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_UPDATERATE(85527,"更新频率,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMDTO_REASON(85528,"创建理由,不能为空"),

    CREATEDATASET_CREATEDATASETPARAMFILEDTO_EDITTYPE(85529,"编辑类型,1新增，2编辑，3详情,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMFILEDTO_ID(85530,"数据集id,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMFILEDTO_FILES(85531,"附件信息,不能为空"),
    CREATEDATASET_CREATEDATASETPARAMFILEDTO_DIRECTORYID(85532,"管理目录id,不能为空"),
    CREATEDATASET_CAN_NOT_EDIT(85533,"审批中的数据集不能编辑"),
    CREATEDATASET_CREATEDSPDBFIRSTREQDTO_DBID(85534," 数据源id,不能为空"),
    CREATEDATASET_CREATEDSPDBFIRSTREQDTO_UPDATETYPE(85535,"更新方式不能为空"),
    CREATEDATASET_DBSOURCE_NOT_HAS(85536,"更新方式不能为空"),

    CREATEDATASET_CREATEDSPDBSECONDREQDTO_EDITTYPE(85537,"编辑类型,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_ID(85538,"数据集id,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_SETMODE(85539,"创建数据集方式,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_TABLECODE(85540,"表名标识,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_DATATYPE(85541,"数据类型,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_RESULTFILENAME(85542,"返回的字段名称列表,不能为空"),
    CREATEDATASET_CREATEDSPDBSECONDREQDTO_SQLCODE(85543,"SQL语句,不能为空"),

    CREATEDATASET_CREATEDSPDBTHIRDREQTDO_EDITTYPE(85544,"编辑类型,不能为空"),
    CREATEDATASET_CREATEDSPDBTHIRDREQTDO_ID(85545,"数据集id,不能为空"),
    CREATEDATASET_CREATEDSPDBTHIRDREQTDO_PARAMFILEDS(85546,"参数字段,不能为空"),
    SELECTDIC_SELECTDIRECTORYREQDTO_ID(85547,"数据集id,不能为空"),
    SELECTDIC_SELECTDIRECTORYREQDTO_DIRECTORY(85548,"选择关联的目录,不能为空"),

    CREATE_DATA_SET_SOURCE_NOT_USER(85549,"数据源不可用"),
    CREATE_DATA_SET_TABLE_CODE_NULL(85550,"表名标识不能为空"),
    CREATE_DATA_SET_TABLE_NOT_HAS(85551,"表不存在"),

    CREATE_DATA_SET_NOT_FILE_SET(85552,"不是文件类数据集"),
    DELETE_DATA_FILE_ID_NOT_FILE_(85553,"文件id列表不能为空"),
    DELETE_DATA_FILE_PARAM_NUMM(85554,"删除文件参数不能为空"),

    DATA_SET_IS_NOT_API(85555,"该数据集不是API"),
    DATA_SET_AUDIT_ADMIN(85556,"单位管理员和平台管理才能审批数据集"),
    DATA_SET_IS_NOT_DATABASE(85557,"该数据集不数据库类型的"),
    DATA_SET_ELEMENT_RULE_NOT_NULL(85558,"数据集字段规则不能为空"),
    DATA_SET_ELEMENT_RULE_DTO_NOT_NULL(85559,"数据集字段规则对象不能为空"),
    DATA_SET_ELEMENT_ID_NOT_NULL(85560,"数据集字段ID不能为空"),
    WARE_HOUSE_OBJ_NOT_NULL(85561,"修改对象不能为空"),

    MODIFY_TABLE_FIELD_FAILE(85562,"修改字段失败"),
    ;

    private int code;
    private String msg;

    ExchangeExceptionCode(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    @Override
    public int getCode() {
        return code;
    }

    @Override
    public String getMsg() {
        return msg;
    }
}
